#!/bin/bash
#	echo "\$SrvBin/nMariaDbDef.sh"
cat >$SrvEtcKnz/$KnN <<EOF
#!/bin/bash
	echo "Start: $KnN -- Generated by: $SrvBin/nMariaDbKnDef.sh"
	
# ??  export KnN=$KnN
export KnRtN=$KnN
export ThisKnCtrlHPFN=\$SrvEtcKnz/\$KnRtN
	echo -e "	Start:  ThisKnCtrlHPFN>>>\$ThisKnCtrlHPFN\n"

export KnPkgN=$KnPkgN
export DkrImgN=$DkrImgN
export DkrRtImgN=$DkrImgN
export KnConfVer=$KnConfVer
export KnKlsPFN=$SrvLib/$KnKlsN.sh

export SvrStkN=$SvrStkN    #Fut: export SvrStkN=Pro  # | Tst | Dev
export KnGrpN=$KnGrpN

export DkrRunDCmd='$DkrRunDCmd'		# mk '' default @@@
export DkrNet=$DkrNet

    # --> ??? export MkKnFQHPFN=/srv/WkSp/CloudFinesse/MariaDB/genMariaDbFiles.sh

# -- Host FSH -- Host Paths ("____HP") 
export RunFQHPFN=\$RunHP/\$KnPkgN	# used to hold rt.envs (w/ CID)

# -- Kn FSH --
export KnBasHP=\$SrvKnz/\$KnRtN
export KnRootHP=\$KnBasHP  # was /tmp/tCF/mDB  # *** Deprecated: use KnBasHP @@@@@@@@@@@@@@

# -- Derived by rule...
#Fut: export FQKnRtN=\${SvrStkN}._.\${KnGrpN}._.\${KnRtN}
export FQKnRtN=\${KnGrpN}._.\${KnRtN}
export DkrRtLbls=" --label stk=\$SvrStkN  --label grp=\$KnGrpN --label kanT=\$KnPkgN "
    #qq export DkrVolGrp=" -v $KnEtcHP/:/etc/$KnPkgN/:ro  -v $KnLogHP/:/var/log/$KnPkgN  
export DkrVolGrp=" -v \$KnBasHP/srv:/srv "
